### PR TITLE
[feat-4756] my incidents extra questions

### PR DESCRIPTION
**Pull request by vdegraaf**
Ticket: [SIG-4756](https://gemeente-amsterdam.atlassian.net/browse/SIG-4756)

## Context
We want to show the additional answers in the detail page of my incidents as well.

## Changes
- Moved some types and logic from incident-management to shared folder.
- Create an ExtraProperties component for my-incidents
- Add tests

### CODE REVIEW

**Review by SireeKoolenWijkstra — COMMENTED** [review]
Hoi Vincent,

De aanvullende vragen worden anders weergegeven in mijn meldingen dan dat in de story staat. Ik denk dat daar nog een vertaalslag overheen gewenst is.
afbeelding

**Comment by vdegraaf** [comment]
@SireeKoolenWijkstra That's correct. This is how we get it back from te backend currently. If we want the full questions, we need a change in the api response I think. Let's discuss this tomorrow in standup. Linda was also not too happy with it;)

**Comment by vdegraaf** [comment]
@SireeKoolenWijkstra Talked to Jelle and we go with this summarized question first and then discuss what to do next.

**Review by SireeKoolenWijkstra — APPROVED** [review]
If Jelle approves, I'm all for it.

**Pull request merged**
