### PR TITLE
add plugin and configuration

### PR DESCRIPTION
**Pull request by vdegraaf**
The import are at the minimal ordered automatically. This PR introduces a plugin and configuration to standardize the imports in .js and .ts files. 

Curious about what you guys think and if we should implement such thing. Some example follow! Should work with any IDE since it is ESLint, but maybe you can double check. You guys use PyCharm, I have VSCode.

- [Configuration](https://dev.to/otamnitram/sorting-your-imports-correctly-in-react-213m) Got the config from this guy.
- [ESLint pluging](https://github.com/import-js/eslint-plugin-import)
- [TS support](https://github.com/import-js/eslint-import-resolver-typescript#installation)

## Example #1
Before             |  After
:-------------------------:|:-------------------------:
Screenshot 2022-08-30 at 13 32 54  |  Screenshot 2022-08-30 at 13 32 24

## Example #2
Before             |  After
:-------------------------:|:-------------------------:
Screenshot 2022-08-30 at 13 39 42  |  Screenshot 2022-08-30 at 13 38 37

## Example #3
Before             |  After
:-------------------------:|:-------------------------:
Screenshot 2022-08-30 at 13 41 21  |  Screenshot 2022-08-30 at 13 41 28

## Example #4
Before             |  After
:-------------------------:|:-------------------------:
Screenshot 2022-08-30 at 13 43 00  |  Screenshot 2022-08-30 at 13 43 13

### CODE REVIEW

**Comment by kiruys** [comment]
I think you should discuss this with Oscar and Siree

**Comment by OscarBakker** [comment]
Great pr, just make sure the current ordering is deleted first.

**Comment by vdegraaf** [comment]
> Great pr, just make sure the current ordering is deleted first.

The current ordering is done by just this line `'import/order': 'error',` which is overwritten in this PR.

**Review by OscarBakker — APPROVED** [review]
Seems good to me.

**Pull request merged**
